contact_us/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'contact_us'

urlpatterns = [
    path('', views.contact_us, name="contact_us"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'gallery'

urlpatterns = [
    path('', views.gallery, name="gallery"),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

innovative_dealership/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from landing_page import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing_page, name='landing_page'),
    path('gallery/', include('gallery.urls')),
    path('contact_us/', include('contact_us.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact_us/models.py
from django.db import models

# Create your models here.

gallery/models.py
from django.db import models

# Create your models here.


class Car(models.Model):
    cartitle = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='all_media/images/')
    price = models.CharField(max_length=9)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.cartitle

landing_page/models.py
from django.db import models

# Create your models here.

contact_us/views.py
from django.shortcuts import render

# Create your views here.


def contact_us(request):
    return render(request, 'contact_us/contact_us.html')

gallery/views.py
from django.shortcuts import render
from .models import Car
# Create your views here.


def gallery(request):
    car = Car.objects.all()
    return render(request, 'gallery/gallery.html', {'cars': car})

landing_page/views.py
from django.shortcuts import render
# Create your views here.


def landing_page(request):
    return render(request, 'landing_page/home.html')

contact_us/templates/contact_us/contact_us.html
{% extends 'landing_page/Base.html' %}
{% block nav%}
{%load static%}
<section id="contactus" class="head pb-5">

    <div class="container py-5">
        <div class="card">
            <div class="card-body">
                <h1 class="font-weight-light text-center py-3">Contact Us</h1>

                <div class="col-lg-6 col-md-12 col-sm-12 col-12">
                    <div class="row pt-3">
                     <div class="col-lg-1 offset-1 col-md-2 col-sm-2 col-2">
                         <span style="font-size: 30px; color: black"><i class="fas fa-map-marker-alt"></i></span>
                     </div>

                        <div class="col-lg-10 col-md-9 col-sm-9 col-9">
                            <h3>Find Our Offices At</h3>
                            <p>18 Old Discovery Rd, Nr4,<br>
                                1724 Discovery,<br>
                                Gauteng
                            </p>
                        </div>

                    </div>
                     <div class="row pt-3">
                     <div class="col-lg-1 offset-1 col-md-2 col-sm-2 col-2">
                         <span style="font-size: 30px; color: black"><i class="fas fa-phone-alt"></i></span>
                     </div>

                        <div class="col-lg-10 col-md-9 col-sm-9 col-9">
                            <h3 class="font-weight-light">Ring Us Up Anytime</h3>
                            <p>Zane Samodien<br>
                                011 125 379<br>
                                Mon - Fri, 9:00 a.m - 17:00 p.m
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6 col-md-12 col-sm-12 ">
                    <form>
                        <div class="form-row">
                            <div class="form-group col-lg-6 col-md-12 col-sm-12 col-12">
                                <label>First Name:</label>
                                <input type="text" class="form-control" placeholder="First Name">
                            </div>

                             <div class="form-group col-lg-6 col-md-12 col-sm-12 col-12">
                                <label>Last Name:</label>
                                <input type="text" class="form-control" placeholder="Last Name">
                            </div>
                        </div>
                        <label>Email</label>
                        <input type="Email" placeholder="Email" class="form-control">
                        <label>Your Message</label>
                        <textarea class="form-control mb-3" placeholder="Message" id ="" cols="30" rows="11"></textarea>
                        <input type="checkbox"> <label>I'm not a robot</label> <button class="btn btn-primary float-right">Send Message</button>
                    </form>
                </div>

                <div class="email text-center" id="email">
                    <a href="https://www.zanesamodien@gmail.com">Send a Direct Email</a>
                </div>

            </div>

        </div>
    </div>
</section>
{%endblock%}

gallery/templates/gallery/gallery.html
{% extends 'landing_page/Base.html' %}
{% block nav%}
{%load static%}
<section id="gallery" class="gallery py-5">
    <div class="container">
        <div class="row">
            <div class="col-10 mx-auto col-sm-6 text-center">
                <h1 class="text-capitalize gallery-title">Gallery</h1>
            </div>
        </div>
        <!--gallery list-->
        <div class="row gallery-items" id="gallery-items">
            <!--single item-->
            <div class="col-10 col-sm-8 col-lg-4 mx-auto my-3">
                <div class="card single-item">
                    <div class="img-container">
                        <img src="{%static 'landing_page/david-von-diemar-bM41B-AKt18-unsplash.jpg'%}" class="card-img-top gallery-img " alt="">
                    </div>
                    <div class="card-body">
            <div class="card-text d-flex justify-content-between text-capitalize">
                <h5 id="item-name">VW Future'X</h5>
                <span> <i class="fas fa-dollar-sign"></i> 800 000</span>
            </div>
                    </div>
                </div>
            </div>
            <!--end single item-->

                    <!--gallery list-->
        <div class="row gallery-items" id="gallery-items">
            <!--single item-->
            <div class="col-10 col-sm-8 col-lg-4 mx-auto my-3">
                <div class="card single-item">
                    <div class="img-container">
                        <img src="{%static 'landing_page/martin-katler-IJ9XaDzU-vg-unsplash.jpg'%}" class="card-img-top gallery-img " alt="">
                    </div>
                    <div class="card-body">
            <div class="card-text d-flex justify-content-between text-capitalize">
                <h5 id="item-name">Golf MK 1</h5>
                <span> <i class="fas fa-dollar-sign"></i> 45 000</span>
            </div>
                    </div>
                </div>
            </div>
            <!--end single item-->

                    <!--gallery list-->
        {% for car in cars %}
            <div class="row gallery-items" id="gallery-items">
                <!--single item-->
                <div class="col-10 col-sm-8 col-lg-4 mx-auto my-3">
                    <div class="card single-item">
                        <div class="img-container">
                            <img src="{{car.image.url}}" class="card-img-top gallery-img " alt="">
                        </div>
                        <div class="card-body">
                <div class="card-text d-flex justify-content-between text-capitalize">
                    <h5 id="item-name">{{car.cartitle}}</h5>
                    <span> <i class="fas fa-dollar-sign"></i>{{car.price}}</span>
                    <p class="card-text"></p>
                </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <!--end single item-->

        </div>
    </div>



</section>

{%endblock%}

landing_page/templates/landing_page/Base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static%}
<!--      <link rel="stylesheet" href="{% static 'css/main.css'%}">-->
    <link rel="stylesheet" href="{%static 'css/main.css'%}">
      <link rel="icon" type="image/png" href="{% static 'landing_page/Logo.jpg' %}">
    <script src="https://kit.fontawesome.com/1cce7401dc.js" crossorigin="anonymous"></script>
    <script src="{% static 'css/javascript.js'%}" crossorigin="anonymous"></script>

    <title>Innovative Dealership</title>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'landing_page'%}">Innovative</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="container">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'landing_page'%}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gallery:gallery'%}">Gallery</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact_us:contact_us'%}">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'gallery:gallery'%}">About</a>
          </li>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"><i class="fas fa-shopping-cart"></i></a>
          </li>
        </ul>
      </div>
    </div>
</nav>


    {% block nav %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

landing_page/templates/landing_page/home.html
{% extends 'landing_page/Base.html' %}
{% block nav%}
{%load static%}
    <section id="main">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{%static 'landing_page/erik-mclean-m6zTTlL8pSg-unsplash.jpg'%}" class="d-block w-100" alt="">


      <div class="carousel-caption d-none d-md-block">
          <h1 class="display-3 title-color"><i>Welcome to Innovative Dealership</i></h1>
        <p class="landingtext" id="landingtext">Home to the Prettiest VDubs for cheap.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'landing_page/julian-hochgesang-gSnyL1T935o-unsplash.jpg'%}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h2>VW Life<br> For Coloureds By Coloureds</h2>
        <p>We have the smoothest and most stanced VDubs</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{%  static 'landing_page/annie-theby-Zpu3yhZsSsM-unsplash.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>You Know You Want One, You can Afford It !!</h5>
        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
    </section>

<hr class="style-eight">

<section class="services py-5 text-center aboutus" id="aboutus">
    <h1 class="services heading text-center">About US</h1>
    <div class="container">
        Volkswagen Group, also called Volkswagen AG, major German automobile manufacturer,
        founded by the German government in 1937 to mass-produce a low-priced “people's car.”
        Headquarters are in Wolfsburg, Germany. A Volkswagen Tiguan being assembled at a factory in Wolfsburg, Germany.
    </div>
</section>
<hr class="style-eight">

<section class="featured products">
    <div class="container for-feats">
        <h1 class="services heading text-center">Most in demand</h1>
        <div class="row">
            <div class="col-10 mx-auto col-md-6 col-lg-4 my-3">
                <div class="card" style="width: 18rem;">
                    <h5 class="card-title">Golf MK 3 </h5>
                  <img src="{% static 'landing_page/sgcdesignco-81Dfucag9OY-unsplash.jpg' %}" class="card-img-top" alt="...">
                  <div class="card-body">
                    <p class="card-text">The Golf MK 3 2000</p>
                    </div>
            </div>
        </div>
            <!--end of single service-->
                 <div class="col-10 mx-auto col-md-6 col-lg-4 my-3">
                <div class="card" style="width: 18rem;">
                    <h5 class="card-title">Polo GTI</h5>
                  <img src="{% static 'landing_page/jose-carbajal-8xyki0bqvgw-unsplash.jpg' %}" class="card-img-top" alt="...">
                  <div class="card-body">
                    <p class="card-text">The Polo GTI 2019</p>
                    </div>
            </div>
        </div>
            <!--end of single service-->

                 <div class="col-10 mx-auto col-md-6 col-lg-4 my-3">
                <div class="card" style="width: 18rem;">
                    <h5 class="card-title">Golf 7 GTI </h5>
                  <img src="{% static 'landing_page/malusi-msomi--J3YbdTjhBY-unsplash.jpg' %}" class="card-img-top" alt="...">
                  <div class="card-body">
                    <p class="card-text">The Golf 7 GTI 2020</p>
                    </div>
            </div>
        </div>
            <!--end of single service-->



        </div>
    </div>
</section>

{%endblock%}